In [9]:
import pandas
import time
from datetime import datetime

dfs = pandas.read_html('http://rate.bot.com.tw/xrt?Lang=zh-TW')

In [71]:
dfs[0]

,幣別,幣別.1,現金匯率,Unnamed: 3,即期匯率,Unnamed: 5,遠期匯率,歷史匯率,歷史匯率.1,現金匯率.1,...,本行買入,本行賣出,本行買入 .1,本行賣出 .1,Unnamed: 18,本行買入,本行賣出,本行買入.1,本行賣出.1,Date
0,美金 (USD) 美金 (USD),31.8,32.342,32.1,32.2,查詢,查詢,31.8,32.342,32.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-24 23:34:53
1,港幣 (HKD) 港幣 (HKD),3.992,4.187,4.112,4.172,查詢,查詢,3.992,4.187,4.112,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-24 23:34:53
2,英鎊 (GBP) 英鎊 (GBP),38.43,40.36,39.3,39.72,查詢,查詢,38.43,40.36,39.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-24 23:34:53
3,澳幣 (AUD) 澳幣 (AUD),22.89,23.55,23.08,23.31,查詢,查詢,22.89,23.55,23.08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-24 23:34:53
4,加拿大幣 (CAD) 加拿大幣 (CAD),23.46,24.2,23.73,23.95,查詢,查詢,23.46,24.2,23.73,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-24 23:34:53
5,新加坡幣 (SGD) 新加坡幣 (SGD),21.72,22.5,22.14,22.32,查詢,查詢,21.72,22.5,22.14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-24 23:34:53
6,瑞士法郎 (CHF) 瑞士法郎 (CHF),30.65,31.71,31.18,31.47,查詢,查詢,30.65,31.71,31.18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-24 23:34:53
7,日圓 (JPY) 日圓 (JPY),0.2653,0.2763,0.2717,0.2757,查詢,查詢,0.2653,0.2763,0.2717,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-24 23:34:53
8,南非幣 (ZAR) 南非幣 (ZAR),-,-,2.25,2.33,查詢,查詢,-,-,2.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-24 23:34:53
9,瑞典幣 (SEK) 瑞典幣 (SEK),3.1,3.61,3.44,3.54,查詢,查詢,3.1,3.61,3.44,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-24 23:34:53
10,紐元 (NZD) 紐元 (NZD),21.87,22.5,22.11,22.31,查詢,查詢,21.87,22.5,22.11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-24 23:34:53
11,泰幣 (THB) 泰幣 (THB),0.7893,0.9323,0.8778,0.9178,查詢,查詢,0.7893,0.9323,0.8778,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-24 23:34:53
12,菲國比索 (PHP) 菲國比索 (PHP),0.5967,0.7297,-,-,查詢,查詢,0.5967,0.7297,-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-24 23:34:53
13,印尼幣 (IDR) 印尼幣 (IDR),0.00208,0.00278,-,-,查詢,查詢,0.00208,0.00278,-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-24 23:34:53
14,歐元 (EUR) 歐元 (EUR),32.86,34.01,33.36,33.76,查詢,查詢,32.86,34.01,33.36,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-24 23:34:53
15,韓元 (KRW) 韓元 (KRW),0.02496,0.02886,-,-,查詢,查詢,0.02496,0.02886,-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-24 23:34:53
16,越南盾 (VND) 越南盾 (VND),0.00104,0.00154,-,-,查詢,查詢,0.00104,0.00154,-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-24 23:34:53
17,馬來幣 (MYR) 馬來幣 (MYR),6.093,7.693,-,-,查詢,查詢,6.093,7.693,-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-24 23:34:53
18,人民幣 (CNY) 人民幣 (CNY),4.529,4.691,4.601,4.651,查詢,查詢,4.529,4.691,4.601,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-12-24 23:34:53

In [72]:
currency = dfs[0]

In [73]:
currency = currency.ix[:,0:5] #選取需要的[row,column]

In [74]:
currency.columns = [u'幣別', u'現金匯率-本行買入', u'現金匯率-本行賣出', u'即期匯率-本行買入', u'即期匯率-本行賣出'] #修改 header

In [75]:
currency[u'幣別'] = currency[u'幣別'].str.extract('\((\w+)\)')

/usr/local/lib/python2.7/site-packages/IPython/kernel/__main__.py:1: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
  if __name__ == '__main__':

In [76]:
currency.to_excel('yen_rate.xlsx')
#count = 1

#while True:
#    filename = 'yen_rate_' + str(count) + '.xlsx'
#    currency.to_excel(filename)
#    time.sleep(1*60)
#    count += 1

In [77]:
currency['Date'] = '123'

In [78]:
datetime.now().strftime('%Y-%m-%d')

'2016-12-24'

In [79]:
#currency['Date'] = datetime.now().strftime('%Y-%m-%d')
currency['Date'] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

In [80]:
currency

     幣別 現金匯率-本行買入 現金匯率-本行賣出 即期匯率-本行買入 即期匯率-本行賣出                 Date
0   USD      31.8    32.342      32.1      32.2  2016-12-24 23:35:22
1   HKD     3.992     4.187     4.112     4.172  2016-12-24 23:35:22
2   GBP     38.43     40.36      39.3     39.72  2016-12-24 23:35:22
3   AUD     22.89     23.55     23.08     23.31  2016-12-24 23:35:22
4   CAD     23.46      24.2     23.73     23.95  2016-12-24 23:35:22
5   SGD     21.72      22.5     22.14     22.32  2016-12-24 23:35:22
6   CHF     30.65     31.71     31.18     31.47  2016-12-24 23:35:22
7   JPY    0.2653    0.2763    0.2717    0.2757  2016-12-24 23:35:22
8   ZAR         -         -      2.25      2.33  2016-12-24 23:35:22
9   SEK       3.1      3.61      3.44      3.54  2016-12-24 23:35:22
10  NZD     21.87      22.5     22.11     22.31  2016-12-24 23:35:22
11  THB    0.7893    0.9323    0.8778    0.9178  2016-12-24 23:35:22
12  PHP    0.5967    0.7297         -         -  2016-12-24 23:35:22
13  IDR   0.00208   0.00278         -         -  2016-12-24 23:35:22
14  EUR     32.86     34.01     33.36     33.76  2016-12-24 23:35:22
15  KRW   0.02496   0.02886         -         -  2016-12-24 23:35:22
16  VND   0.00104   0.00154         -         -  2016-12-24 23:35:22
17  MYR     6.093     7.693         -         -  2016-12-24 23:35:22
18  CNY     4.529     4.691     4.601     4.651  2016-12-24 23:35:22

In [81]:
currency.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 6 columns):
幣別           19 non-null object
現金匯率-本行買入    19 non-null object
現金匯率-本行賣出    19 non-null object
即期匯率-本行買入    19 non-null object
即期匯率-本行賣出    19 non-null object
Date         19 non-null object
dtypes: object(6)
memory usage: 984.0+ bytes

In [82]:
currency['Date'] = pandas.to_datetime(currency['Date']) #修改資料庫欄位類型

In [83]:
currency.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 6 columns):
幣別           19 non-null object
現金匯率-本行買入    19 non-null object
現金匯率-本行賣出    19 non-null object
即期匯率-本行買入    19 non-null object
即期匯率-本行賣出    19 non-null object
Date         19 non-null datetime64[ns]
dtypes: datetime64[ns](1), object(5)
memory usage: 984.0+ bytes

In [87]:
import sqlite3

#寫入 yen_rate 資料庫
with sqlite3.connect('currency.sqlite') as db:
    currency.to_sql('yen_rate', con = db, if_exists='append')

In [88]:
#讀取 yen_rate 資料庫
with sqlite3.connect('currency.sqlite') as db:
    df = pandas.read_sql_query('select * from yen_rate', con = db)

In [89]:
df

    index   幣別 現金匯率-本行買入 現金匯率-本行賣出 即期匯率-本行買入 即期匯率-本行賣出                 Date
0       0  USD      31.8    32.342      32.1      32.2  2016-12-24 23:35:22
1       1  HKD     3.992     4.187     4.112     4.172  2016-12-24 23:35:22
2       2  GBP     38.43     40.36      39.3     39.72  2016-12-24 23:35:22
3       3  AUD     22.89     23.55     23.08     23.31  2016-12-24 23:35:22
4       4  CAD     23.46      24.2     23.73     23.95  2016-12-24 23:35:22
5       5  SGD     21.72      22.5     22.14     22.32  2016-12-24 23:35:22
6       6  CHF     30.65     31.71     31.18     31.47  2016-12-24 23:35:22
7       7  JPY    0.2653    0.2763    0.2717    0.2757  2016-12-24 23:35:22
8       8  ZAR         -         -      2.25      2.33  2016-12-24 23:35:22
9       9  SEK       3.1      3.61      3.44      3.54  2016-12-24 23:35:22
10     10  NZD     21.87      22.5     22.11     22.31  2016-12-24 23:35:22
11     11  THB    0.7893    0.9323    0.8778    0.9178  2016-12-24 23:35:22
12     12  PHP    0.5967    0.7297         -         -  2016-12-24 23:35:22
13     13  IDR   0.00208   0.00278         -         -  2016-12-24 23:35:22
14     14  EUR     32.86     34.01     33.36     33.76  2016-12-24 23:35:22
15     15  KRW   0.02496   0.02886         -         -  2016-12-24 23:35:22
16     16  VND   0.00104   0.00154         -         -  2016-12-24 23:35:22
17     17  MYR     6.093     7.693         -         -  2016-12-24 23:35:22
18     18  CNY     4.529     4.691     4.601     4.651  2016-12-24 23:35:22